//! Spec-driven code generation: turn a [`crate::spec::Spec`] into the
//! mechanical Rust files of a `sw-{slug}-isa` crate.
//!
//! Step 5 (`scaffolder-codegen`). For `encoding_style = "bit_fields"`, emits
//! working `encode.rs` / `decode.rs` / `lib.rs` with `Architecture` impl.
//! For `encoding_style = "rom_table"` (COR24), emits opcode/register/branch
//! tables but stubs encode/decode (those are hand-supplied per
//! `gen-isa/docs/decisions.md` Sec 14).

use crate::spec::{
    EncodingStyle, Endian, Field, FieldKind, Format, LengthDispatch, RegClass, Spec,
};
use std::fmt::Write as _;

/// Generated `src/opcode.rs`.
pub fn opcode_rs(spec: &Spec) -> String {
    let mut out = String::new();
    out.push_str("//! Opcode enum and metadata.\n");
    out.push_str("//!\n");
    out.push_str("//! Generated by gen-isa from the ISA spec; do not edit by hand.\n");
    out.push_str("//! Re-run the scaffolder to regenerate.\n\n");

    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq)]\n");
    out.push_str("#[repr(u8)]\n");
    out.push_str("pub enum Opcode {\n");
    for op in &spec.opcodes {
        let _ = writeln!(out, "    {} = 0x{:02X},", op.name, op.value);
    }
    out.push_str("}\n\n");

    out.push_str("impl Opcode {\n");

    // mnemonic()
    out.push_str("    pub fn mnemonic(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for op in &spec.opcodes {
        let _ = writeln!(
            out,
            "            Opcode::{} => \"{}\",",
            op.name, op.mnemonic
        );
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    // formats()
    out.push_str("    pub fn formats(self) -> &'static [&'static str] {\n");
    out.push_str("        match self {\n");
    for op in &spec.opcodes {
        let names = op.format_names();
        let arr = names
            .iter()
            .map(|n| format!("\"{n}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "            Opcode::{} => &[{arr}],", op.name);
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    // try_from_value(): byte -> first matching opcode (note: ambiguous if
    // values repeat across formats; spec validation does not forbid that
    // globally, so we use first-declared-wins).
    out.push_str("    pub fn try_from_value(v: u8) -> Option<Self> {\n");
    out.push_str("        match v {\n");
    let mut seen_values = std::collections::BTreeSet::new();
    for op in &spec.opcodes {
        if seen_values.insert(op.value) {
            let _ = writeln!(
                out,
                "            0x{:02X} => Some(Opcode::{}),",
                op.value, op.name
            );
        }
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");

    out.push_str("}\n\n");

    // Mnemonic trait impl
    out.push_str("impl sw_isa_core::Mnemonic for Opcode {\n");
    out.push_str("    fn mnemonic(&self) -> &'static str {\n");
    out.push_str("        Opcode::mnemonic(*self)\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Generated `src/register.rs`.
pub fn register_rs(spec: &Spec) -> String {
    let mut out = String::new();
    out.push_str("//! Register definitions.\n");
    out.push_str("//!\n");
    out.push_str("//! Generated by gen-isa from the ISA spec; do not edit by hand.\n\n");

    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq)]\n");
    out.push_str("pub enum Reg {\n");
    for r in &spec.registers {
        let _ = writeln!(out, "    {},", pascal(&r.name));
    }
    out.push_str("}\n\n");

    out.push_str("#[derive(Copy, Clone, Debug, Eq, PartialEq)]\n");
    out.push_str("pub enum RegClass {\n");
    out.push_str("    Gpr, Acc, Ext, Xr, Reserved, Pc, Sp, Fp, Flags,\n");
    out.push_str("}\n\n");

    out.push_str("impl Reg {\n");
    out.push_str("    pub fn name(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for r in &spec.registers {
        let _ = writeln!(
            out,
            "            Reg::{} => \"{}\",",
            pascal(&r.name),
            r.name
        );
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn class(self) -> RegClass {\n");
    out.push_str("        match self {\n");
    for r in &spec.registers {
        let _ = writeln!(
            out,
            "            Reg::{} => RegClass::{},",
            pascal(&r.name),
            class_variant(r.class)
        );
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("impl sw_isa_core::register::RegisterId for Reg {\n");
    out.push_str("    fn index(self) -> u32 {\n");
    out.push_str("        match self {\n");
    for r in &spec.registers {
        let _ = writeln!(out, "            Reg::{} => {},", pascal(&r.name), r.index);
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    fn name(self) -> &'static str {\n");
    out.push_str("        Reg::name(self)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub fn parse_register(s: &str) -> Option<Reg> {\n");
    out.push_str("    match s {\n");
    for r in &spec.registers {
        let _ = writeln!(
            out,
            "        \"{}\" => Some(Reg::{}),",
            r.name,
            pascal(&r.name)
        );
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Generated `src/branch.rs`.
pub fn branch_rs(spec: &Spec) -> String {
    let max_bytes = spec.memory.max_instr_bytes;
    format!(
        "//! Branch range constants.\n\
         //!\n\
         //! Generated by gen-isa from the ISA spec; do not edit by hand.\n\
         \n\
         pub const BRANCH_OFFSET_MIN: i32 = {};\n\
         pub const BRANCH_OFFSET_MAX: i32 = {};\n\
         pub const MAX_INSTRUCTION_BYTES: usize = {max_bytes};\n\
         pub const MAX_SHORT_BRANCH_INSTRUCTIONS: usize = {};\n\
         pub const PIPELINE_DELAY_BYTES: u32 = {};\n\
         \n\
         pub fn can_short_branch(from: usize, to: usize) -> bool {{\n\
         \x20   from.abs_diff(to) <= MAX_SHORT_BRANCH_INSTRUCTIONS\n\
         }}\n",
        spec.branch.short_offset_min,
        spec.branch.short_offset_max,
        spec.branch.max_short_branch_instructions,
        spec.branch.pipeline_delay_bytes,
    )
}

/// Generated `src/encode.rs`.
pub fn encode_rs(spec: &Spec) -> String {
    if spec.encoding.style == EncodingStyle::RomTable {
        return rom_table_encode_stub();
    }
    let mut out = String::new();
    out.push_str("//! Encoding helpers.\n");
    out.push_str("//!\n");
    out.push_str("//! Generated by gen-isa from the ISA spec.\n\n");
    out.push_str("use crate::Instruction;\n");
    out.push_str("use crate::opcode::Opcode;\n");
    out.push_str("use sw_isa_core::EncodeError;\n\n");

    // Top-level dispatch
    out.push_str(
        "pub fn encode(insn: &Instruction, out: &mut [u8]) -> Result<usize, EncodeError> {\n",
    );
    out.push_str("    match insn {\n");
    for f in &spec.formats {
        let variant = pascal(&f.name);
        let fields = encodable_fields(f);
        let pat: String = fields
            .iter()
            .map(|fld| fld.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        let args: String = fields
            .iter()
            .map(|fld| format!("*{}", fld.name))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "        Instruction::{variant} {{ {pat} }} => encode_{}({args}, out),",
            f.name
        );
    }
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Per-format encoders
    for f in &spec.formats {
        emit_format_encoder(&mut out, f, spec);
    }
    out
}

fn rom_table_encode_stub() -> String {
    "//! Encoding helpers.\n\
     //!\n\
     //! `encoding_style = \"rom_table\"`: encoding is hand-supplied, not generated\n\
     //! from the spec (per gen-isa/docs/decisions.md Sec 14). Fill in below.\n\
     \n\
     use crate::Instruction;\n\
     use sw_isa_core::EncodeError;\n\
     \n\
     pub fn encode(_insn: &Instruction, _out: &mut [u8]) -> Result<usize, EncodeError> {\n\
     \x20   // TODO (rom_table): hand-supply per-opcode encoding.\n\
     \x20   Err(EncodeError::InvalidOperands)\n\
     }\n"
    .to_string()
}

fn emit_format_encoder(out: &mut String, f: &Format, spec: &Spec) {
    let total_bits = (f.size_bytes * 8) as u32;
    let int_ty = uint_type_for_bits(total_bits);
    let endian_method = match spec.memory.endian {
        Endian::Big => "to_be_bytes",
        Endian::Little => "to_le_bytes",
    };
    let fields = encodable_fields(f);
    let args: String = fields
        .iter()
        .map(|fld| format!("{}: {}", fld.name, field_type(fld)))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "fn encode_{name}({args}, out: &mut [u8]) -> Result<usize, EncodeError> {{\n\
         \x20   if out.len() < {bytes} {{ return Err(EncodeError::BufferTooSmall); }}\n\
         \x20   let mut word: {int_ty} = 0;",
        name = f.name,
        bytes = f.size_bytes,
    );
    for fld in &f.fields {
        let shift = total_bits - fld.offset - fld.width;
        let mask = if fld.width == 64 {
            u64::MAX
        } else {
            (1u64 << fld.width) - 1
        };
        match fld.kind {
            FieldKind::Reserved => {
                let value = fld.value.unwrap_or(0);
                let _ = writeln!(
                    out,
                    "    word |= ({value}{int_ty} & 0x{mask:X}) << {shift};",
                );
            }
            FieldKind::Indirect => {
                let _ = writeln!(
                    out,
                    "    word |= (({} as {int_ty}) & 0x{mask:X}) << {shift};",
                    fld.name
                );
            }
            FieldKind::Disp => {
                if fld.signed {
                    let cast_to = uint_type_for_bits(fld.width);
                    let _ = writeln!(
                        out,
                        "    word |= (({} as {cast_to} as {int_ty}) & 0x{mask:X}) << {shift};",
                        fld.name
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "    word |= (({} as {int_ty}) & 0x{mask:X}) << {shift};",
                        fld.name
                    );
                }
            }
            FieldKind::Imm | FieldKind::Tag | FieldKind::Reg | FieldKind::Opcode => {
                let _ = writeln!(
                    out,
                    "    word |= (({} as {int_ty}) & 0x{mask:X}) << {shift};",
                    fld.name
                );
            }
        }
    }
    let _ = writeln!(
        out,
        "    out[..{bytes}].copy_from_slice(&word.{endian_method}());\n\
         \x20   Ok({bytes})\n\
         }}\n",
        bytes = f.size_bytes,
    );
}

/// Generated `src/decode.rs`.
pub fn decode_rs(spec: &Spec) -> String {
    if spec.encoding.style == EncodingStyle::RomTable {
        return rom_table_decode_stub();
    }
    let mut out = String::new();
    out.push_str("//! Decoding helpers.\n");
    out.push_str("//!\n");
    out.push_str("//! Generated by gen-isa from the ISA spec.\n\n");
    out.push_str("use crate::{Instruction, opcode::Opcode};\n");
    out.push_str("use sw_isa_core::DecodeError;\n\n");

    out.push_str("pub fn decode(bytes: &[u8]) -> Result<(Instruction, usize), DecodeError> {\n");

    if spec.encoding.length_dispatch == LengthDispatch::FirstWordBits {
        emit_first_word_dispatch(&mut out, spec);
    } else {
        emit_per_opcode_dispatch(&mut out, spec);
    }

    out.push_str("}\n\n");

    for f in &spec.formats {
        emit_format_decoder(&mut out, f, spec);
    }
    out
}

fn rom_table_decode_stub() -> String {
    "//! Decoding helpers.\n\
     //!\n\
     //! `encoding_style = \"rom_table\"`: decoding is hand-supplied. Fill in below.\n\
     \n\
     use crate::Instruction;\n\
     use sw_isa_core::DecodeError;\n\
     \n\
     pub fn decode(_bytes: &[u8]) -> Result<(Instruction, usize), DecodeError> {\n\
     \x20   // TODO (rom_table): hand-supply per-opcode decoding.\n\
     \x20   Err(DecodeError::Invalid)\n\
     }\n"
    .to_string()
}

fn emit_first_word_dispatch(out: &mut String, spec: &Spec) {
    let first_word_bytes = (spec.memory.word_bits / 8) as usize;
    let int_ty = uint_type_for_bits(spec.memory.word_bits);
    let endian_method = match spec.memory.endian {
        Endian::Big => "from_be_bytes",
        Endian::Little => "from_le_bytes",
    };
    let _ = writeln!(
        out,
        "    if bytes.len() < {first_word_bytes} {{ return Err(DecodeError::Truncated); }}",
    );
    let arr_args: String = (0..first_word_bytes)
        .map(|i| format!("bytes[{i}]"))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "    let first_word = {int_ty}::{endian_method}([{arr_args}]);",
    );
    out.push_str("    ");
    let mut first = true;
    for f in &spec.formats {
        let disc = f
            .discriminator
            .as_ref()
            .expect("validated: first_word_bits requires discriminator");
        let shift = (spec.memory.word_bits) - disc.offset - disc.width;
        let mask = if disc.width == 64 {
            u64::MAX
        } else {
            (1u64 << disc.width) - 1
        };
        if !first {
            out.push_str(" else ");
        }
        first = false;
        let _ = write!(
            out,
            "if ((first_word >> {shift}) & 0x{mask:X}) == {value} {{\n        decode_{name}(bytes)\n    }}",
            value = disc.value,
            name = f.name,
        );
    }
    out.push_str(" else {\n        Err(DecodeError::Invalid)\n    }\n");
}

fn emit_per_opcode_dispatch(out: &mut String, spec: &Spec) {
    out.push_str("    if bytes.is_empty() { return Err(DecodeError::Truncated); }\n");
    out.push_str("    let op = bytes[0];\n");
    out.push_str("    let opcode = Opcode::try_from_value(op).ok_or(DecodeError::Invalid)?;\n");
    out.push_str("    match opcode.formats().first().copied() {\n");
    for f in &spec.formats {
        let _ = writeln!(
            out,
            "        Some(\"{}\") => decode_{}(bytes),",
            f.name, f.name
        );
    }
    out.push_str("        _ => Err(DecodeError::Invalid),\n");
    out.push_str("    }\n");
}

fn emit_format_decoder(out: &mut String, f: &Format, spec: &Spec) {
    let total_bits = (f.size_bytes * 8) as u32;
    let int_ty = uint_type_for_bits(total_bits);
    let endian_method = match spec.memory.endian {
        Endian::Big => "from_be_bytes",
        Endian::Little => "from_le_bytes",
    };
    let bytes = f.size_bytes;
    let _ = writeln!(
        out,
        "fn decode_{name}(bytes: &[u8]) -> Result<(Instruction, usize), DecodeError> {{",
        name = f.name,
    );
    let _ = writeln!(
        out,
        "    if bytes.len() < {bytes} {{ return Err(DecodeError::Truncated); }}",
    );
    let arr_args: String = (0..bytes)
        .map(|i| format!("bytes[{i}]"))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "    let word = {int_ty}::{endian_method}([{arr_args}]);",
    );

    // Extract opcode field first so we can look up the Opcode variant.
    let mut have_op = false;
    for fld in &f.fields {
        if fld.kind == FieldKind::Opcode {
            let shift = total_bits - fld.offset - fld.width;
            let mask = if fld.width == 64 {
                u64::MAX
            } else {
                (1u64 << fld.width) - 1
            };
            let _ = writeln!(
                out,
                "    let op_value = ((word >> {shift}) & 0x{mask:X}) as u8;",
            );
            out.push_str(
                "    let op = Opcode::try_from_value(op_value).ok_or(DecodeError::Invalid)?;\n",
            );
            have_op = true;
            break;
        }
    }
    if !have_op {
        out.push_str("    // No opcode field declared in this format.\n");
    }

    // Extract other (non-reserved, non-opcode) fields.
    for fld in &f.fields {
        if matches!(fld.kind, FieldKind::Reserved | FieldKind::Opcode) {
            continue;
        }
        let shift = total_bits - fld.offset - fld.width;
        let mask = if fld.width == 64 {
            u64::MAX
        } else {
            (1u64 << fld.width) - 1
        };
        let cast = field_type(fld);
        match fld.kind {
            FieldKind::Indirect => {
                let _ = writeln!(
                    out,
                    "    let {name} = ((word >> {shift}) & 0x{mask:X}) != 0;",
                    name = fld.name,
                );
            }
            FieldKind::Disp if fld.signed => {
                let intermediate = uint_type_for_bits(fld.width);
                let _ = writeln!(
                    out,
                    "    let {name} = (((word >> {shift}) & 0x{mask:X}) as {intermediate}) as {cast};",
                    name = fld.name,
                );
            }
            _ => {
                let _ = writeln!(
                    out,
                    "    let {name} = ((word >> {shift}) & 0x{mask:X}) as {cast};",
                    name = fld.name,
                );
            }
        }
    }

    // Build the variant.
    let variant = pascal(&f.name);
    let fields = encodable_fields(f);
    let constructor: String = fields
        .iter()
        .map(|fld| fld.name.clone())
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "    Ok((Instruction::{variant} {{ {constructor} }}, {bytes}))",
    );
    out.push_str("}\n\n");
}

/// Generated `src/lib.rs` (overrides the step-4 stub when --spec is given).
pub fn lib_rs(spec: &Spec, type_name: &str, slug: &str) -> String {
    let mut out = String::new();
    let display_name = &spec.arch.display_name;
    let _ = writeln!(
        out,
        "//! `sw-{slug}-isa`: ISA description for {display_name}.\n\
         //!\n\
         //! Generated by gen-isa. Trait surface: `sw_isa_core::Architecture`."
    );
    out.push('\n');
    out.push_str("pub mod opcode;\n");
    out.push_str("pub mod register;\n");
    out.push_str("pub mod encode;\n");
    out.push_str("pub mod decode;\n");
    out.push_str("pub mod branch;\n\n");
    out.push_str("pub use opcode::Opcode;\n");
    out.push_str("pub use register::{Reg, parse_register};\n\n");

    // Address newtype.
    out.push_str(
        "/// Newtype address; arithmetic is in address-units (see\n\
         /// `Architecture::ADDRESS_UNIT`), not bytes.\n\
         #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]\n\
         pub struct Addr(pub u32);\n\n\
         impl sw_isa_core::address::AddressType for Addr {\n\
         \x20   fn to_u64(self) -> u64 { self.0 as u64 }\n\
         \x20   fn from_u64(v: u64) -> Self { Addr(v as u32) }\n\
         \x20   fn step(self, n: i64) -> Self { Addr((self.0 as i64 + n) as u32) }\n\
         }\n\n",
    );

    // Marker arch type.
    let _ = writeln!(
        out,
        "#[derive(Copy, Clone, Debug, Eq, PartialEq)]\n\
         pub struct {type_name};\n",
    );

    // Instruction enum: one variant per format. Fields = encodable (non-reserved) fields.
    if spec.encoding.style == EncodingStyle::BitFields {
        out.push_str("\n#[derive(Copy, Clone, Debug, Eq, PartialEq)]\npub enum Instruction {\n");
        for f in &spec.formats {
            let fields = encodable_fields(f);
            let body: String = fields
                .iter()
                .map(|fld| format!("{}: {}", fld.name, field_type(fld)))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                out,
                "    {variant} {{ {body} }},",
                variant = pascal(&f.name),
            );
        }
        out.push_str("}\n");
    } else {
        // rom_table: stub Instruction. Hand-fill.
        out.push_str(
            "\n/// Stub Instruction enum for rom_table mode. Hand-fill\n\
             /// per the existing implementation (e.g. sw-cor24-isa::decode).\n\
             #[derive(Copy, Clone, Debug, Eq, PartialEq)]\n\
             pub struct Instruction;\n",
        );
    }

    // Architecture impl.
    let _ = writeln!(out);
    out.push_str("impl sw_isa_core::Architecture for ");
    out.push_str(type_name);
    out.push_str(" {\n");
    out.push_str("    type Opcode = opcode::Opcode;\n");
    out.push_str("    type Register = register::Reg;\n");
    out.push_str("    type Instruction = Instruction;\n");
    out.push_str("    type Address = Addr;\n");
    out.push_str("    type Format = sw_isa_core::format::Length;\n\n");

    let _ = writeln!(
        out,
        "    const NAME: &'static str = \"{}\";",
        spec.arch.display_name
    );
    let _ = writeln!(
        out,
        "    const ENDIAN: sw_isa_core::endian::Endian = sw_isa_core::endian::Endian::{};",
        spec.memory.endian.rust_variant(),
    );
    let _ = writeln!(
        out,
        "    const ADDRESS_UNIT: sw_isa_core::address::AddressUnit = sw_isa_core::address::AddressUnit::{};",
        spec.memory.address_unit.rust_variant(),
    );
    let _ = writeln!(out, "    const WORD_BITS: u32 = {};", spec.memory.word_bits);
    let _ = writeln!(
        out,
        "    const MIN_INSTR_BYTES: usize = {};",
        spec.memory.min_instr_bytes
    );
    let _ = writeln!(
        out,
        "    const MAX_INSTR_BYTES: usize = {};",
        spec.memory.max_instr_bytes
    );

    out.push_str(
        "\n    fn decode(bytes: &[u8], _pc: Self::Address)\n\
         \x20       -> Result<(Self::Instruction, usize), sw_isa_core::DecodeError>\n\
         \x20   {\n\
         \x20       decode::decode(bytes)\n\
         \x20   }\n\n",
    );
    out.push_str(
        "    fn encode(insn: &Self::Instruction, out: &mut [u8])\n\
         \x20       -> Result<usize, sw_isa_core::EncodeError>\n\
         \x20   {\n\
         \x20       encode::encode(insn, out)\n\
         \x20   }\n\n",
    );

    // disassemble: stub
    if spec.encoding.style == EncodingStyle::BitFields {
        out.push_str(
            "    fn disassemble(insn: &Self::Instruction, w: &mut dyn core::fmt::Write)\n\
             \x20       -> core::fmt::Result\n\
             \x20   {\n",
        );
        out.push_str("        match insn {\n");
        for f in &spec.formats {
            let fields = encodable_fields(f);
            let pat: String = fields
                .iter()
                .map(|fld| fld.name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            let placeholders: String = fields
                .iter()
                .map(|fld| format!("{}={{:?}}", fld.name))
                .collect::<Vec<_>>()
                .join(" ");
            let args_print: String = fields
                .iter()
                .map(|fld| fld.name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            let variant = pascal(&f.name);
            if fields.is_empty() {
                let _ = writeln!(
                    out,
                    "            Instruction::{variant} {{}} => write!(w, \"<{}>\"),",
                    variant
                );
            } else {
                let _ = writeln!(
                    out,
                    "            Instruction::{variant} {{ {pat} }} => write!(w, \"<{} {placeholders}>\", {args_print}),",
                    variant
                );
            }
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
    } else {
        out.push_str(
            "    fn disassemble(_insn: &Self::Instruction, w: &mut dyn core::fmt::Write)\n\
             \x20       -> core::fmt::Result\n\
             \x20   {\n\
             \x20       w.write_str(\"<rom_table: hand-supplied disassembly>\")\n\
             \x20   }\n",
        );
    }

    out.push_str("}\n");
    out
}

/// Generated `tests/roundtrip.rs`. Curated set per format; passes for
/// bit_fields specs, marked `#[ignore]` for rom_table specs.
pub fn roundtrip_test(spec: &Spec, type_name: &str, slug: &str) -> String {
    if spec.encoding.style == EncodingStyle::RomTable {
        return format!(
            "//! Round-trip tests. rom_table mode: encode/decode are hand-supplied.\n\
             //! Tests are #[ignore]'d until the hand-supplied versions land.\n\
             \n\
             #[test]\n\
             #[ignore = \"rom_table: encode/decode hand-supplied\"]\n\
             fn rom_table_roundtrip() {{\n\
             \x20   // Hand-author cases once encode/decode are filled in.\n\
             \x20   let _ = \"sw-{slug}-isa\";\n\
             \x20   let _ = stringify!({type_name});\n\
             }}\n",
        );
    }
    let crate_under = format!("sw_{}_isa", slug.replace('-', "_"));
    let mut out = String::new();
    out.push_str("//! Round-trip tests: encode(decode(x)) == x for a curated set.\n");
    out.push_str("//!\n");
    out.push_str("//! Generated by gen-isa. Extend with reference vectors from the\n");
    out.push_str("//! authoritative ISA manual as the implementation matures.\n\n");
    let _ = writeln!(
        out,
        "use {crate_under}::{{{type_name}, Instruction, Opcode, Addr}};"
    );
    out.push_str("use sw_isa_core::Architecture;\n\n");

    // For each format, emit one curated roundtrip case using the first
    // opcode that supports that format.
    for f in &spec.formats {
        let variant = pascal(&f.name);
        let opcode = spec
            .opcodes
            .iter()
            .find(|op| op.format_names().iter().any(|n| *n == f.name));
        let Some(op) = opcode else { continue };
        let fields = encodable_fields(f);
        let constructor: String = fields
            .iter()
            .map(|fld| {
                let v = sample_value_with_opcode(fld, &op.name);
                format!("{}: {v}", fld.name)
            })
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "#[test]\n\
             fn roundtrip_{}() {{\n\
             \x20   let ins = Instruction::{variant} {{ {constructor} }};\n\
             \x20   let mut buf = [0u8; {bytes}];\n\
             \x20   let n = {type_name}::encode(&ins, &mut buf).unwrap();\n\
             \x20   let (decoded, m) = {type_name}::decode(&buf[..n], Addr(0)).unwrap();\n\
             \x20   assert_eq!(n, m);\n\
             \x20   assert_eq!(decoded, ins);\n\
             }}\n",
            f.name,
            bytes = f.size_bytes,
        );
    }
    out
}

// ---------- helpers ----------

fn pascal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut up = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            up = true;
            continue;
        }
        if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn class_variant(c: RegClass) -> &'static str {
    match c {
        RegClass::Gpr => "Gpr",
        RegClass::Acc => "Acc",
        RegClass::Ext => "Ext",
        RegClass::Xr => "Xr",
        RegClass::Reserved => "Reserved",
        RegClass::Pc => "Pc",
        RegClass::Sp => "Sp",
        RegClass::Fp => "Fp",
        RegClass::Flags => "Flags",
    }
}

fn encodable_fields(f: &Format) -> Vec<&Field> {
    f.fields
        .iter()
        .filter(|fld| fld.kind != FieldKind::Reserved)
        .collect()
}

fn field_type(fld: &Field) -> &'static str {
    match fld.kind {
        FieldKind::Opcode => "Opcode",
        FieldKind::Indirect => "bool",
        FieldKind::Disp if fld.signed => match fld.width {
            1..=8 => "i8",
            9..=16 => "i16",
            17..=32 => "i32",
            _ => "i64",
        },
        _ => match fld.width {
            1..=8 => "u8",
            9..=16 => "u16",
            17..=32 => "u32",
            _ => "u64",
        },
    }
}

fn uint_type_for_bits(bits: u32) -> &'static str {
    match bits {
        1..=8 => "u8",
        9..=16 => "u16",
        17..=32 => "u32",
        33..=64 => "u64",
        _ => "u64",
    }
}

fn sample_value_with_opcode(fld: &Field, opcode_name: &str) -> String {
    match fld.kind {
        FieldKind::Opcode => format!("Opcode::{opcode_name}"),
        FieldKind::Indirect => "false".to_string(),
        FieldKind::Disp if fld.signed => "0i8".to_string(),
        _ => "0".to_string(),
    }
}
